CREATE TABLE tool_generic (
	id SERIAL NOT NULL,
	uri VARCHAR NOT NULL,
	name VARCHAR NOT NULL,
	version VARCHAR NOT NULL,
	description TEXT,
	types VARCHAR[] NOT NULL,
	location VARCHAR NOT NULL,
	input_file_formats VARCHAR[],
	output_file_formats VARCHAR[],
	input_file_descriptions VARCHAR[],
	output_file_descriptions VARCHAR[],
	input_slots JSONB,
	output_slots JSONB,
	license VARCHAR,
	keywords VARCHAR[],
	tags VARCHAR[],
	raw_definition JSONB,
	raw_metadata JSONB,
	metadata_schema JSONB,
	metadata_type VARCHAR,
	metadata_version VARCHAR,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	updated_at TIMESTAMP WITH TIME ZONE,
	created_by VARCHAR,
	PRIMARY KEY (id),
	UNIQUE (uri)
)
