-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/export_db_schema.py from
-- https://github.com/EOSC-Data-Commons/data-commons-search/blob/main/src/data_commons_search/db.py

CREATE INDEX datasets_alternate_identifiers_idx ON datasets USING gin (alternate_identifiers);

CREATE INDEX datasets_bm25_search_text_idx ON datasets USING bm25 (search_text) WITH (text_config = 'english');

CREATE INDEX datasets_bm25_title_idx ON datasets USING bm25 (title) WITH (text_config = 'english');

CREATE INDEX datasets_creators_idx ON datasets USING gin (creators);

CREATE INDEX datasets_doi_idx ON datasets (doi) WHERE doi IS NOT NULL;

CREATE INDEX datasets_keywords_idx ON datasets USING gin (keywords);

CREATE INDEX datasets_publication_year_idx ON datasets (publication_year);

CREATE INDEX datasets_repository_code_idx ON datasets (repository_code);

CREATE INDEX datasets_resource_type_idx ON datasets (resource_type);

CREATE INDEX datasets_source_updated_at_idx ON datasets (source_updated_at);

CREATE INDEX record_embeddings_diskann_idx ON record_embeddings USING diskann (embedding vector_cosine_ops, labels);
