-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/export_db_schema.py from
-- https://github.com/EOSC-Data-Commons/data-commons-search/blob/main/src/data_commons_search/db.py

CREATE TABLE rate_limits (
	key VARCHAR(255) NOT NULL,
	count INTEGER NOT NULL,
	window_end TIMESTAMP WITH TIME ZONE NOT NULL,
	PRIMARY KEY (key)
);

CREATE TABLE users (
	sub VARCHAR(255) NOT NULL,
	email VARCHAR(320),
	name VARCHAR(255),
	username VARCHAR(255),
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	aup_accepted TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (sub)
);

CREATE TABLE conversations (
	user_id VARCHAR(255) NOT NULL,
	thread_id VARCHAR(255) NOT NULL,
	label VARCHAR(255) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (user_id, thread_id),
	FOREIGN KEY(user_id) REFERENCES users (sub) ON DELETE CASCADE
);

CREATE TABLE messages (
	id SERIAL NOT NULL,
	user_id VARCHAR(255) NOT NULL,
	thread_id VARCHAR(255) NOT NULL,
	type VARCHAR(64) NOT NULL,
	content JSONB NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id, thread_id) REFERENCES conversations (user_id, thread_id) ON DELETE CASCADE
);

CREATE TABLE datasets (
	url VARCHAR(2048) NOT NULL,
	doi VARCHAR(255),
	title TEXT NOT NULL,
	alt_titles TEXT[] DEFAULT '{}' NOT NULL,
	description TEXT,
	keywords TEXT[] DEFAULT '{}' NOT NULL,
	creators TEXT[] DEFAULT '{}' NOT NULL,
	creator_identifiers TEXT[] DEFAULT '{}' NOT NULL,
	alternate_identifiers TEXT[] DEFAULT '{}' NOT NULL,
	resource_type VARCHAR(64) NOT NULL,
	publication_year SMALLINT,
	publication_date DATE,
	languages VARCHAR(8)[] DEFAULT '{}' NOT NULL,
	formats TEXT[] DEFAULT '{}' NOT NULL,
	license TEXT,
	license_url TEXT,
	repository_code VARCHAR(50) NOT NULL,
	repository_name VARCHAR(255) NOT NULL,
	search_text TEXT NOT NULL,
	source_record_id VARCHAR(510) NOT NULL,
	source_datestamp TIMESTAMP WITH TIME ZONE NOT NULL,
	source_updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
	indexed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT datasets_pkey PRIMARY KEY (url),
	CONSTRAINT datasets_doi_not_url_check CHECK (doi IS NULL OR doi NOT LIKE 'http%'),
	CONSTRAINT datasets_source_record_id_key UNIQUE (source_record_id)
);

COMMENT ON TABLE datasets IS 'Query-ready datasets for hybrid search, projected from datasetdb.records';
COMMENT ON COLUMN datasets.url IS 'Landing page URL, or https://doi.org/<doi> for records that only have a DOI';
COMMENT ON COLUMN datasets.doi IS 'Bare DOI without resolver prefix, nullable';
COMMENT ON COLUMN datasets.creator_identifiers IS 'ORCID/ROR/etc identifiers of the creators, same order as creators when known';
COMMENT ON COLUMN datasets.alternate_identifiers IS 'Other identifiers of the dataset itself (alternateIdentifiers), for lookups and dedup';
COMMENT ON COLUMN datasets.search_text IS 'Text fields concatenated for BM25 (pg_textsearch)';
COMMENT ON COLUMN datasets.source_record_id IS 'datasetdb.records.id this row was built from';
COMMENT ON COLUMN datasets.source_updated_at IS 'datasetdb.records.updated_at at indexing time, to detect outdated rows';

CREATE TABLE record_embeddings (
	record_url VARCHAR(2048) NOT NULL,
	field dataset_embedding_field NOT NULL,
	chunk_index SMALLINT DEFAULT 0 NOT NULL,
	chunk_text TEXT NOT NULL,
	embedding VECTOR(768) NOT NULL,
	model VARCHAR(100) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	labels SMALLINT[] GENERATED ALWAYS AS (ARRAY[CASE field WHEN 'title' THEN 1 WHEN 'description' THEN 2 WHEN 'keywords' THEN 3 END]::SMALLINT[]) STORED NOT NULL,
	CONSTRAINT record_embeddings_pkey PRIMARY KEY (record_url, field, chunk_index),
	CONSTRAINT record_embeddings_record_url_fkey FOREIGN KEY(record_url) REFERENCES datasets (url) ON DELETE CASCADE
);

COMMENT ON TABLE record_embeddings IS 'Named embeddings per record, several chunks per field when the text is too long';
COMMENT ON COLUMN record_embeddings.field IS 'Name of the embedded field, mapped to a diskann label';
COMMENT ON COLUMN record_embeddings.chunk_text IS 'Exact text sent to the embedding model';
COMMENT ON COLUMN record_embeddings.labels IS 'Generated from field, for pgvectorscale filtered search: WHERE labels && ARRAY[1]';
