-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/export_db_schema.py from
-- https://github.com/EOSC-Data-Commons/data-commons-search/blob/main/src/data_commons_search/db.py

-- ============================================
-- EXTENSIONS
-- ============================================
-- Extensions used for hybrid search in postgres (installed in the image built by
-- docker/postgres/Dockerfile, pg_textsearch also needs shared_preload_libraries).

-- vector column type + HNSW/IVFFlat indexes
CREATE EXTENSION IF NOT EXISTS vector;

-- StreamingDiskANN index for vector similarity search (depends on vector)
CREATE EXTENSION IF NOT EXISTS vectorscale;

-- BM25 ranked full text search
CREATE EXTENSION IF NOT EXISTS pg_textsearch;

-- ============================================
-- TYPES
-- ============================================

-- Named embeddings stored per dataset. The labels mapping generated in the
-- record_embeddings.labels column (tables.sql) is derived from the same list, so each value
-- always gets its own label number.
DO $$ BEGIN
    CREATE TYPE dataset_embedding_field AS ENUM ('title', 'description', 'keywords');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;
