[project]
name = "metadata-warehouse-transformer"
version = "0.0.1"
description = "Prepare and import DataCite OAI-PMH XML metadata into PostgreSQL and OpenSearch"
requires-python = ">=3.12"
dependencies = [
    "opensearch-py>=3.1.0",
    "celery>=5.6.2",
    "xmltodict>=1.0.4",
    "jsonschema>=4.26.0",
    "fastembed>=0.7.4",
    "watchdog>=6.0.0",
    "fastapi[standard]>=0.135.1",
    "psycopg[binary]>=3.3.3",
    # "flower", # only needed when not using mher/flower
    "datahugger-ng>=0.6.3",
    "docker>=7.1.0",
    "requests>=2.32.5",
    "lxml>=6.0.2",
    "alembic>=1.18.4",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "types-xmltodict>=1.0.1.20260113",
    "celery-stubs>=0.1.3",
    "mypy>=1.19.1",
    "types-jsonschema>=4.26.0.20260202",
    "types-requests>=2.32.4.20260107",
    "lxml-stubs>=0.5.1",
    "python-dotenv>=1.2.2",
    "celery-types>=0.24.0",
    "ruff>=0.15.12",
    "pre-commit>=4.6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.hatch.build.targets.wheel]
packages = ["src", "config", "scheduler"]

[tool.mypy]
python_version = "3.12"
strict = true

mypy_path = ["src"]
explicit_package_bases = true
namespace_packages = true

files = [
    "src",
    "scheduler",
    "config"
]

# https://docs.astral.sh/ruff/configuration
[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.format]
quote-style = "single"

# https://docs.astral.sh/ruff/rules/
[tool.ruff.lint]

ignore = [
    'E501', # formatter uses best-effort wrapping; avoid lint/format churn
    'C417', # allow map() instead of list comprehensions
]

select = [
    "I",     # isort
    "N",     # pep8-naming
    "S",     # bandit
    "A",     # flake8-builtins
    "YTT",   # flake8-2020
    "B",     # flake8-bugbear
    "C",     # flake8-comprehensions
    "ICN",   # flake8-import-conventions
    "SIM",   # flake8-simplify
    "TID",   # flake8-tidy-imports
    "FBT",   # flake8-boolean-trap
    "T",     # flake8-debugger & flake8-print~
    "F",     # pyflakes
    "UP",    # pyupgrade
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "PLC",   # pylint convention
    "PLE",   # pylint error
    "PLW",   # pylint warning
    "RUF",   # ruff specific
]

[tool.ruff.lint.per-file-ignores]
# Prevent __init__.py from being flagged for unused imports and sorted
"__init__.py" = ["I", "F401"]
# Tests can use assertions and magic values
'**/{tests,e2e}/*' = ['S101']
