-- ============================================
-- 6. SAMPLE DATA
-- ============================================

-- Sample repository
INSERT INTO repositories (name, code, description, base_url, is_active)
VALUES
    ('Data Archiving and Networked Services', 'DANS', 'Dutch national archive for research data', 'https://dans.knaw.nl', true),
    ('Digital Academic Repository', 'DABAR', 'Croatian national repository', 'https://dabar.srce.hr', true),
    ('SwissUbase', 'SWISS', 'Swiss data repository', 'https://www.swissubase.ch', true),
    ('HAL Science', 'HAL', 'French open archive', 'https://hal.science', true),
    ('Onedata', 'ONE', 'Onedata demo repository', 'https://demo.onedata.org', true),
    ('FinBIF', 'FINBIF', 'Finnish Biodiversity Information Facility', 'https://laji.fi', true),
    ('Zenodo', 'ZENODO', 'Zenodo repository', 'https://zenodo.org', true),
    ('PaNOSC', 'PANOSC', 'Scientific data infrastructure repository', 'https://www.panosc.eu/', true),
    ('Dataverse Latvia EOSC Node', 'DATAVERSELV', 'Latvian research data repository', 'https://dataverse.lv/', true),
    ('Molecular Dynamics Data Bank', 'MDDB', 'Unified database of the data generated by molecular dynamics simulations', 'https://mddbr.eu/', true),
    ('DaSCH', 'DASCH', 'DaSCH metadata repository', 'https://dasch.swiss', true)

ON CONFLICT (code) DO NOTHING;


-- DANS Archaeology
INSERT INTO endpoints (
    repository_id, name, harvest_url, protocol,
    scientific_discipline, is_active, harvest_params, harvest_schedule
)
SELECT
    r.id,
    'Archaeology Data Station',
    'https://archaeology.datastations.nl/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite", "additional_metadata_params": {"endpoint": "https://archaeology.datastations.nl/api/datasets/:persistentId/versions/:latest-published", "protocol": "DATAVERSE_API", "format": "dataverse_json"}}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'DANS'
ON CONFLICT (name) DO NOTHING;


-- DANS Social Sciences Data Station
INSERT INTO endpoints (
    repository_id, name, harvest_url, protocol,
    scientific_discipline, is_active, harvest_params, harvest_schedule
)
SELECT
    r.id,
    'Social Sciences Data Station',
    'https://ssh.datastations.nl/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite", "additional_metadata_params": {"endpoint": "https://ssh.datastations.nl/api/datasets/:persistentId/versions/:latest-published", "protocol": "DATAVERSE_API", "format": "dataverse_json"}}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'DANS'
ON CONFLICT (name) DO NOTHING;


-- DANS Life Sciences
INSERT INTO endpoints (
    repository_id, name, harvest_url, protocol,
    scientific_discipline, is_active, harvest_params, harvest_schedule
)
SELECT
    r.id,
    'Life Sciences',
    'https://lifesciences.datastations.nl/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite", "additional_metadata_params": {"endpoint": "https://lifesciences.datastations.nl/api/datasets/:persistentId/versions/:latest-published", "protocol": "DATAVERSE_API", "format": "dataverse_json"}}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'DANS'
ON CONFLICT (name) DO NOTHING;


-- DANS Physical and Technical Sciences
INSERT INTO endpoints (
    repository_id, name, harvest_url, protocol,
    scientific_discipline, is_active, harvest_params, harvest_schedule
)
SELECT
    r.id,
    'Physical and Technical Sciences',
    'https://phys-techsciences.datastations.nl/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite", "additional_metadata_params": {"endpoint": "https://phys-techsciences.datastations.nl/api/datasets/:persistentId/versions/:latest-published", "protocol": "DATAVERSE_API", "format": "dataverse_json"}}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'DANS'
ON CONFLICT (name) DO NOTHING;


-- DANS Generalist
INSERT INTO endpoints (
    repository_id, name, harvest_url, protocol,
    scientific_discipline, is_active, harvest_params, harvest_schedule
)
SELECT
    r.id,
    'Generalist',
    'https://dataverse.nl/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite", "additional_metadata_params": {"endpoint": "https://dataverse.nl/api/datasets/:persistentId/versions/:latest-published", "protocol": "DATAVERSE_API", "format": "dataverse_json"}}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'DANS'
ON CONFLICT (name) DO NOTHING;


-- SwissUbase
INSERT INTO endpoints (
    repository_id, name, harvest_url, protocol,
    scientific_discipline, is_active, harvest_params, harvest_schedule
)
SELECT
    r.id,
    'SwissUbase',
    'https://www.swissubase.ch/oai-pmh/v1/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_ddi25"}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'SWISS'
ON CONFLICT (name) DO NOTHING;


-- DABAR
INSERT INTO endpoints (
    repository_id, name, harvest_url, protocol,
    scientific_discipline, is_active, harvest_params, harvest_schedule
)
SELECT
    r.id,
    'DABAR',
    'https://dabar.srce.hr/oai/',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite", "set": ["openaire"], "additional_metadata_params": {"endpoint": "https://dabar.srce.hr/oai/", "protocol": "OAI-PMH", "format": "mods"}}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'DABAR'
ON CONFLICT (name) DO NOTHING;


-- HAL
INSERT INTO endpoints (
    repository_id, name, harvest_url, protocol,
    scientific_discipline, is_active, harvest_params, harvest_schedule
)
SELECT
    r.id,
    'HAL',
    'https://api.archives-ouvertes.fr/oai/hal',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite", "set": ["collection:LINKED_RESEARCH_OUTPUTS"], "additional_metadata_params": {"endpoint": "https://api.archives-ouvertes.fr/search/", "protocol": "HAL_API", "format": "halId_s,fileMain_s,files_s,fileType_s,modifiedDate_tdate,producedDate_tdate,version_i"}}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'HAL'
ON CONFLICT (name) DO NOTHING;


-- Onedata
INSERT INTO endpoints (
    repository_id, name, harvest_url, protocol,
    scientific_discipline, is_active, harvest_params, harvest_schedule
)
SELECT
    r.id,
    'Onedata',
    'https://demo.onedata.org/oai_pmh',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite", "set": ["2a3d4828965cf74d7fc00d19c15715e7ch3d8e", "a93d0c2877c38910bd10bc458e266debch24b6", "6606a96229a922e4c757c0c99e593318ch4848", "551edb7ebcc12cc859b157854b24f539ch0c34"]}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'ONE'
ON CONFLICT (name) DO NOTHING;


-- FinBIF
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'FinBIF',
    'https://api.gbif.org',
    'FINBIF_API',
    'Biology',
    true,
    '{"metadata_prefix": "oai_datacite"}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'FINBIF'
ON CONFLICT (name) DO NOTHING;


-- Zenodo
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule, depends_on_endpoint_id, dependency_xpath, dependency_match_pattern, dependency_static_dois)
SELECT
    r.id,
    'Zenodo',
    'https://zenodo.org/oai2d',
    'OAI-PMH',
    'Multidisciplinary',
    false,
    '{"metadata_prefix": "oai_datacite", "additional_metadata_params": {"endpoint": "https://zenodo.org/api/records", "protocol": "ZENODO_API", "format": "None"}}',
    INTERVAL '1 week',
    (SELECT id FROM endpoints WHERE name = 'HAL'),
    '/oai:record//datacite:relatedIdentifiers/datacite:relatedIdentifier/text()',
    '%zenodo%',
    ARRAY['10.5281/zenodo.7350485', '10.5281/zenodo.13692761','10.5281/zenodo.15324029', '10.5281/zenodo.7702229', '10.5281/zenodo.11278072', '10.5281/zenodo.3382874', '10.5281/zenodo.6645396', '10.5281/zenodo.8260741', '10.5281/zenodo.4559324', '10.5281/zenodo.20509715']
FROM repositories r
WHERE r.code = 'ZENODO'
ON CONFLICT (name) DO NOTHING;


-- PaNOSc ALBA
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'ALBA',
    'https://data.cells.es/iws/icat_plus/oaipmh/request',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite"}',
    INTERVAL '52 week'
FROM repositories r
WHERE r.code = 'PANOSC'
ON CONFLICT (name) DO NOTHING;


-- PaNOSc DESY
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'DESY',
    'https://public-data.desy.de/oaipmh/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_dc"}',
    INTERVAL '52 week'
FROM repositories r
WHERE r.code = 'PANOSC'
ON CONFLICT (name) DO NOTHING;


-- PaNOSc Elettra
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'Elettra',
    'https://api.opendata.elettra.eu/oaipmh/',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_dc"}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'PANOSC'
ON CONFLICT (name) DO NOTHING;


-- PaNOSc ESRF
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'ESRF',
    'https://icatplus.esrf.fr/oaipmh/request',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite"}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'PANOSC'
ON CONFLICT (name) DO NOTHING;


-- PaNOSc ESS
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'ESS',
    'https://oai.panosc.ess.eu/openaire/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite"}',
    INTERVAL '52 week'
FROM repositories r
WHERE r.code = 'PANOSC'
ON CONFLICT (name) DO NOTHING;


-- PaNOSc EuXFEL
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'EuXFEL',
    'https://in.xfel.eu/metadata/oai-pmh/oai2',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite"}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'PANOSC'
ON CONFLICT (name) DO NOTHING;


-- PaNOSc HZB
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'HZB',
    'https://data.helmholtz-berlin.de/oaipmh/request',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite", "set" : ["pub"]}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'PANOSC'
ON CONFLICT (name) DO NOTHING;


-- PaNOSc HZDR
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'HZDR',
    'https://rodare.hzdr.de/oai2d',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite4", "set": ["openaire_data"]}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'PANOSC'
ON CONFLICT (name) DO NOTHING;


-- PaNOSc ILL
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'ILL',
    'https://fairdata.ill.fr/openaire/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite"}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'PANOSC'
ON CONFLICT (name) DO NOTHING;


-- PaNOSc ISIS
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'ISIS',
    'https://icat.isis.stfc.ac.uk/oaipmh/request',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite"}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'PANOSC'
ON CONFLICT (name) DO NOTHING;


-- PaNOSc MAX IV
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'MAX IV',
    'https://scicat.maxiv.lu.se/openaire/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite"}',
    INTERVAL '52 week'
FROM repositories r
WHERE r.code = 'PANOSC'
ON CONFLICT (name) DO NOTHING;


-- PaNOSc PSI
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'PSI',
    'https://doi.psi.ch/oaipmh/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_dc"}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'PANOSC'
ON CONFLICT (name) DO NOTHING;


-- DataverseLV
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'DataverseLV',
    'https://dv.dataverse.lv/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite", "additional_metadata_params": {"endpoint": "https://dv.dataverse.lv/api/datasets/:persistentId/versions/:latest-published", "protocol": "DATAVERSE_API", "format": "dataverse_json"}}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'DATAVERSELV'
ON CONFLICT (name) DO NOTHING;


-- DataverseLV Riga
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'Riga Stradins University',
    'https://dataverse.rsu.lv/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite", "additional_metadata_params": {"endpoint": "https://dv.dataverse.lv/api/datasets/:persistentId/versions/:latest-published", "protocol": "DATAVERSE_API", "format": "dataverse_json"}}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'DATAVERSELV'
ON CONFLICT (name) DO NOTHING;


-- DataverseLV CLARIN-IV
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'CLARIN-IV',
    'https://repository.clarin.lv/repository/oai/request',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_dc"}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'DATAVERSELV'
ON CONFLICT (name) DO NOTHING;

-- MDDB
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'MDposit',
    'https://mdposit.mddbr.eu/api/rest/v1',
    'MDPOSIT_API',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite"}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'MDDB'
ON CONFLICT (name) DO NOTHING;

-- DaSCH
INSERT INTO endpoints (repository_id, name, harvest_url, protocol, scientific_discipline, is_active, harvest_params, harvest_schedule)
SELECT
    r.id,
    'DaSCH',
    'https://repository.dasch.swiss/dpe/oai',
    'OAI-PMH',
    'Multidisciplinary',
    true,
    '{"metadata_prefix": "oai_datacite","set": ["entityType:ResearchProject"]}',
    INTERVAL '1 week'
FROM repositories r
WHERE r.code = 'DASCH'
ON CONFLICT (name) DO NOTHING;
