---------------------------------------------------------
-- CREATE GOLOBAL USERS
CREATE ROLE reggie LOGIN PASSWORD 'reggie' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE jusong LOGIN PASSWORD 'jusong' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE ritwik LOGIN PASSWORD 'ritwik' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE tobias LOGIN PASSWORD 'tobias' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE josip LOGIN PASSWORD 'josip' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE michal LOGIN PASSWORD 'michal' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE ping LOGIN PASSWORD 'ping' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE vincent LOGIN PASSWORD 'vincent' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE eko LOGIN PASSWORD 'eko' NOSUPERUSER NOCREATEDB NOCREATEROLE;
-- System service accounts
CREATE ROLE script LOGIN PASSWORD 'script'
  NOSUPERUSER NOCREATEDB NOCREATEROLE;